### ISSUE TITLE
Network error on chrome

### ISSUE THREAD

**Issue by AustinGitHub** [TalipOrdu/Speech_Recognition#1]
Hi, this runs into network error on chrome browser and doesn't work on firefox. My internet is completely fine but this doesn't seem to work. You might need to fix it so that it works. I tried the demo app site and this is where I'm seeing this issue. I'm running into this issue on my own too and trying to see if anyone has overcome this issue. Thanks!

**Comment by TalipOrdu** [comment]
Hi, firstly thanks for your interesting, I worked on chrome like you, and
it works but I didn't try it on firefox I'll looking for a solution I hope
find a solution,
Are you working on a Speech recognition App or something like that?

Austin ***@***.***>, 12 Şub 2023 Paz, 22:47 tarihinde şunu
yazdı:

**Comment by AustinGitHub** [comment]
Hi Yes, I'm trying to create a speech recognition type function where a user can say something it can run a simple function and then I will expand from there on it. 
I tried on pure chrome and it seems to work but on chromium based browser like brave it seems to have an issue, I will have to look into my brave settings and see why, do you know if it makes any special protocol server requests for the browser in order for it to work? Maybe hardware acceleration has to be off, I am not sure. I will have to try again later, hoping this is a browser issue that I can fix and that brave browser didn't block this. 

Thanks!
I will close issue as I have found the solution and just need to do further research on it, thanks!
